name: Multiarch build docker image

on:
  push:
    branches: ['stable-5', 'main', '*issue*']

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/ronoaldo/minetestserver

jobs:
  multiarch-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            tags: |-
              unstable
              dev
            platforms: |-
              linux/amd64
              linux/arm64
          - dockerfile: Dockerfile.stable-5
            tags: |-
              stable
              stable-5
            platforms: |-
              linux/amd64
              linux/arm64
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Minetest version/branch
        id: minetest-version
        run: |
          export MINETEST_VERSION="$(grep MINETEST_VERSION= Dockerfile.stable-5 | cut -f 2 -d=)"
          echo "::set-output name=version::${MINETEST_VERSION}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            ${{ steps.minetest-version.outputs.version }}
            ${{ matrix.tags }}

      - name: Check build tags
        id: build-tags-check
        shell: bash
        run: |
          echo ${{ steps.meta.outputs.tags }}

      - name: Set up QEMU for multiarch builds
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   if: ${{ github.ref_name == 'main' || github.ref_name == 'stable-5' }}
      #   with:
      #     context: .
      #     file: ${{ matrix.dockerfile }}
      #     platforms: ${{ matrix.platforms }}
      #     push: ${{ github.ref_name == 'main' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
